# Generated by Django 4.2.3 on 2023-07-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Ork', 'Ork'), ('Furri', 'Furri'), ('Iron', 'Iron')], default='Ork', max_length=50)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
