# Generated by Django 4.2.3 on 2023-08-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('prices', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' цена')),
                ('created', models.DateField(auto_now_add=True)),
                ('descriptions', models.TextField(verbose_name='описание')),
                ('update', models.DateField(auto_now=True)),
                ('auction', models.BooleanField(help_text='Уместен ли торг', verbose_name='merch')),
                ('image', models.ImageField(upload_to='advertisements/', verbose_name='изображения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add.user')),
            ],
        ),
    ]
