# Generated by Django 4.2.3 on 2023-08-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='Advertisement',
        ),
    ]
