# Generated by Django 4.2.3 on 2023-07-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('prices', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' цена')),
                ('created', models.DateField(auto_now_add=True)),
                ('descriptions', models.TextField(verbose_name='описание')),
                ('update', models.DateField(auto_now=True)),
                ('auction', models.BooleanField(help_text='Уместен ли торг', verbose_name='merch')),
            ],
        ),
    ]
