# Generated by Django 4.2.3 on 2023-07-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0002_advertisement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='Advertisements',
        ),
    ]
