# Generated by Django 4.2.3 on 2023-08-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0004_advertisements_cats_delete_advertisement_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table='advertisement',
        ),
    ]
