# Generated by Django 4.2.3 on 2024-03-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0006_alter_advertisement_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='auction',
            field=models.BooleanField(help_text='Уместен ли торг', verbose_name='Торг'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='descriptions',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='advertisements/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='prices',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=' Цена'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
